# Generated by Django 3.2.11 on 2022-02-07 20:07

from django.db import migrations


def transfer_projects(apps, schema_editor):
    Issue = apps.get_model('issue_tracker.Issue')
    Project = apps.get_model('issue_tracker.Project')
    project = Project.objects.create(title='my project', description='me own project', start_date='2021-01-01')
    for issue in Issue.objects.all():
        issue.project = project
        issue.save()


def rollback_transfer(apps, schema_editor):
    Issue = apps.get_model('issue_tracker.Issue')
    for issue in Issue.objects.all():
        issue.project = None
        issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_issue_project'),
    ]

    operations = [
        migrations.RunPython(transfer_projects, rollback_transfer),
    ]
