# Generated by Django 3.2.11 on 2022-02-08 11:30

from django.db import migrations, models
import issue_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_alter_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True, validators=[issue_tracker.validators.MinLengthValidator(3)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=500, validators=[issue_tracker.validators.MinLengthValidator(3)], verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, validators=[issue_tracker.validators.MinLengthValidator(3)], verbose_name='Description'),
        ),
    ]
